### ISSUE TITLE
timeout doesn't seem to work

### ISSUE THREAD

**Issue by Nowaker** [abates/ruby_expect#3]
```
    ssh = RubyExpect::Expect.spawn("/usr/bin/ssh #@user@#@host", :debug => true)
    ssh.timeout = 5
```

My connection hangs on:
```
Uncommitted changes found, commit them before exiting(yes/no/cancel)? [cancel]:
```

I don't have any rule for this question, so it's expected it will hang. However, timeout should recover from it, and kill the process.

**Comment by abates** [comment]
I'm going to close this.  The timeout appears to work in every test that I run.
