### ISSUE TITLE
"global" expectation

### ISSUE THREAD

**Issue by Nowaker** [abates/ruby_expect#4]
I configure a Cisco router. You do that by calling `configure` command in which you interactively write the configuration, e.g. (pseudocode):

```
cisco# configure
cisco:config# bundle-ether 1.2
cisco:config-bundle# ip 1.2.3.4
cisco:config-bundle# blah x
cisco:config-bundle# exit
cisco:config# commit
Configuration applied.
cisco:config#exit
cisco# (we are back to the shell)
```

I need to run ~10 configure commands like that, one after another, so I use `each` method from you gem. Pseudocode:

```
each do
  prompt = /^cisco#/
 
  expect prompt do
    # configure ether-bundle
  end
  expect prompt do
    # configure another ether-bundle
  end
  expect prompt do
    # configure VRF
  end
end
```

Whenever a prompt appears (after I `commit` and `exit` from `configure`), I need to configure the next. (`any` wouldn't work here as it would always pick the first rule) However, when configuration is invalid (e.g. the user provided some invalid input values for bundle-ether or whatever), a question may appear at random time, when in `configure`. By random I mean a moment when you don't expect it, and you keep sending the configuration directives. After I send an invalid configuration, I won't get a prompt. I may get one of these:

- Uncommitted changes found, commit them before exiting(yes/no/cancel)? [cancel]:
- or some other, don't remember it now

...and I am stuck. :)

Is there a possibility to have `each` (one configuration applied after another, whenever prompt is presented) as long as a "global" handler (something like `any`) at the same time? I guess not, but would that be easy to implement? If you give me a few hints, maybe I am able to do that myself.

**Comment by abates** [comment]
I realize this is a year late, but better late than never.  Why wouldn't you just create a driver class to do this?  I'm thinking something like the following:

```ruby
class IOSConfigurer
  def initialize username, password, device
    @exp = RubyExpect::Expect.spawn("/usr/bin/ssh")
    @error = false
    # do login stuff here
  end

  def issue_command command
    unless (@error)
      @exp.send(command)
      @exp.any do
        expect normal_prompt do
          # do nothing maybe?
        end
        expect error_prompt do
          @error = true
          # recover from error here, if it isn't recoverable then all future
          # commands are skipped.  If recoverable, set @error to false
        end
      end
    end
  end
end

configurer = IOSConfigurer.new("username", "password", "router")

# If an error happens anywhere in the following, then @error is set
# in the configurer and subsuquent commands are skipped
# send_command can recover from the error then it just needs to
# set @error to false
configurer.issue_command("comand1")
configurer.issue_command("comand2")
configurer.issue_command("comand3")
configurer.issue_command("comand4")
```
