### ISSUE TITLE
interact (as from original expect)

### ISSUE THREAD

**Issue by geronime** [abates/ruby_expect#5]
Hello,

I have not found if it is possible to do something like the original expect has: `interact` command which hands control over to the user. Would it be possible to have it in the gem?

Thanks,

geronime

**Comment by abates** [comment]
Can you provide an example of how you'd use this?  I think it's possible, I just want to make sure I fully understand. 

Andrew

**Comment by abates** [comment]
Commit 3802441109afea5cfdd6f0476d9aefb1b9d39f11 provides basic interact ability (with some caveats regarding terminal emulation).  Can you pull the develop branch and see if this works for you?

Regards,
Andrew

**Comment by abates** [comment]
I actually improved the implementation slightly in commit b3a376372d0e0c778cf779c04047696b5da2a980.  Please let me know what you think.

Regards,
Andrew

**Comment by geronime** [comment]
Working perfectly. Maybe I would recommend to document that `interact` sholuld be invoked in `expect` block - took me a minute to figure that out.

Thanks a lot!

**Comment by thehappycoder** [comment]
Thanks a lot for this feature! I used it to make automatic login via telnet.

**Comment by abates** [comment]
I added an example on the README that documents simple usage.
