### ISSUE TITLE
leave ssh <defunct> after Expect exit. 

### ISSUE THREAD

**Issue by zongzw** [abates/ruby_expect#7]
For every exit RubyExpect::Expect.spawn would leave a ssh <defunct>. 
Tested with the sample you give.

**Comment by abates** [comment]
When I run the example code it does not leave any defunct ssh sessions:

```shell
user@ubuntu-16-04-base:~/local/src/playground$ ps ax|grep -i ssh|grep -v sshd|grep -v grep
user@ubuntu-16-04-base:~/local/src/playground$ ./expect_test.rb
load average: 0.00, 0.21, 0.17
user@ubuntu-16-04-base:~/local/src/playground$ ps ax|grep -i ssh|grep -v sshd|grep -v grep
user@ubuntu-16-04-base:~/local/src/playground$
```

I'm using Ubuntu 16.04 with Ruby 2.4.1p111

Please provide more information so I can attempt to reproduce your issue.  Please include os information (os, distribution, version) as well as ruby version.

**Comment by abates** [comment]
Closing. No response.
